default_language_version:
  python: python3.13
fail_fast: true
repos:

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, jupyter, pyi]
        args: [--fix]

      # Run the formatter.
      - id: ruff-format
        types_or: [python, jupyter, pyi]

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        exclude: (src/codemods/eval)|(tests/unit/skills/snapshots)|(tests/unit/codegen/sdk/output)|(tests/integration/verified_codemods)|(docs/samples)
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.6
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: tests/
        exclude_types: [mdx, pyi]
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: (src/codemods/eval)|(tests/unit/skills/snapshots)|(tests/unit/codegen/sdk/output)|(tests/integration/verified_codemods)|(docs/)
      - id: check-merge-conflict

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
        args: ["--verbose"]

  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        files: "docs/.*/.*.mdx"

  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.23.0"
    hooks:
      - id: deptry
        pass_filenames: false
        always_run: true
        entry: bash -c "uv run --frozen --all-extras --dev deptry src --ignore DEP001"


  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.158.1
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.5.27"
    hooks:
      - id: uv-sync
        args: ["--frozen", "--all-packages", "--all-extras"]

  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v1.1.0
    hooks:
      - id: circleci_validate
  - repo: "local"
    hooks:
      - id: disallowed-words-check
        name: Check for disallowed words
        entry: scripts/disallowed-words-check.sh
        language: script
        files: ''  # Check all files
      - id: generate-runner-imports
        name: Generate Runner Imports
        entry: bash -c "uv run --frozen python -m codegen.gscli.cli generate runner-imports src/codegen/shared/compilation/function_imports.py"
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-ruff
      - mdformat-config
      - mdformat-pyproject
